title: Epicycle's --dry-run
author: pi.epicycle
email: pi.epicycle@pm.me
description: >

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from
#  - jekyll-feed

minima-reboot:
  date_format: "%b %d, %Y"
  date_format_short: "%b %-d"

header_pages:
  - about.markdown
  - posts.markdown

paginate: 5

markdown: kramdown

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#analytics:
#  provider: "google-gtag"
#  google:
#    measurement_id: "G-L9VS5163X7"

google_analytics: UA-208526362-1

lang: ko
timezone: Asia/Seoul

#host: 192.168.0.46
host: 127.0.0.1
port: 4000
